### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by Sethsmagic** [kaelaela/OpenGraphView#8]
It appears that only the urls displayed in the demo display images. Any other URL that I test (such as reddit or google) don't show an image. Can this be fixed? Everything else is great! Thanks

**Comment by kaelaela** [comment]
@omeedterainsights I'll fix it! Please wait.

**Comment by droid-wise** [comment]
Hello,
Thanks for this library.
Is this problem is solved? 
Because I have experienced the same problem.
